ex12 js is ready
azzelena/external-courses pull request #24
Opened 2018-11-14 20:35 UTC by azzelena

2018-11-15 08:39 UTC, DairoGrey requested changes
Для задания с эвентами нужно использовать делегирование.

2018-11-15 08:39 UTC, DairoGrey commented on src/ex12_js/task-01.js
> +var accord = document.getElementsByClassName("accordion");
А где делегирование события?

2018-11-19 14:48 UTC, azzelena commented on src/ex12_js/task-01.js
> +var accord = document.getElementsByClassName("accordion");
Переделала с делегированием :)

2018-11-19 15:24 UTC, DairoGrey requested changes

2018-11-19 15:24 UTC, DairoGrey commented on src/ex12_js/task-04.js
> +     if(typeof tags[element.tagName] === 'undefined') {
А зачем **typeof**? Сравнения с просто **undefined** разве не хватит?

2018-11-19 15:24 UTC, DairoGrey commented on src/ex12_js/task-04.js
> +             if (child.nodeType === 1) {
Непонятное сравнение. Посмотри пример: https://developer.mozilla.org/ru/docs/Web/API/Node/nodeType

2018-11-19 18:43 UTC, azzelena commented on src/ex12_js/task-04.js
> +     if(typeof tags[element.tagName] === 'undefined') {
Точно! Исправила:)

2018-11-19 19:54 UTC, azzelena commented on src/ex12_js/task-04.js
> +             if (child.nodeType === 1) {
Я просто использовала именно номера node, как здесь https://learn.javascript.ru/basic-dom-node-properties :) Но поменяла на названия:) Теперь все ок

2018-11-21 08:49 UTC, DairoGrey approved these changes

2018-11-23 17:39 UTC, merged