ex14 is ready
azzelena/external-courses pull request #25
Opened 2018-11-24 15:43 UTC by azzelena

2018-11-25 08:14 UTC, DairoGrey requested changes

2018-11-25 08:14 UTC, DairoGrey commented on src/ex14_js-context/task-02.js
> +        this.word = input.toLowerCase();
Здесь и в самом начале ф-ции **Hangman** логика одинаковая, лучше избавиться от дублирования.

2018-11-26 08:59 UTC, azzelena commented on src/ex14_js-context/task-02.js
> +        this.word = input.toLowerCase();
Исправила:) Убрала дублирование в методе

2018-11-27 17:37 UTC, DairoGrey requested changes

2018-11-27 17:37 UTC, DairoGrey commented on src/ex14_js-context/task-02.js
> +        this.word = inputSecond.toLowerCase();
Вместо дублирования логики в самом начале конструктора и в этом методе, помести всю логику, которая отвечает за инициализацию состояния тут, а в конструкторе в самом конце просто вызови этот метод.

2018-11-27 18:38 UTC, azzelena commented on src/ex14_js-context/task-02.js
> +        this.word = inputSecond.toLowerCase();
Точно!! Спасибо, исправила :)

2018-11-27 18:41 UTC, DairoGrey approved these changes

2018-11-27 18:42 UTC, merged